### ISSUE TITLE
Problem running runipy <notebook> --html

### ISSUE THREAD

**Issue by bjonen** [paulgb/runipy#58] opened 2015-04-08 13:15 UTC
I get the following traceback running the above command with runipy 0.1.3: 
```
C:\Python\lib\site-packages\IPython\nbconvert\preprocessors\coalescestreams.pyc in wrappedfunc(nb, resources)
     26                 "Applying preprocessor: %s", function.__name__
     27             )
---> 28         for index, cell in enumerate(nb.cells):
     29             nb.cells[index], resources = function(cell, resources, index)
     30         return nb, resources

C:\Python\lib\site-packages\IPython\utils\ipstruct.pyc in __getattr__(self, key)
    147             result = self[key]
    148         except KeyError:
--> 149             raise AttributeError(key)
    150         else:
    151             return result

AttributeError: cells
```

**Comment by desilinguist** [comment] 2015-04-10 15:02
This sounds like a bug with iPython because the `nb` attribute for `nb_runner` does not have the `cells` attribute anymore. One needs to do `nb['worksheets'][0]['cells']` to get there. 

For now, I got around it by first writing the notebook (`nb_runner.nb`) to a temporary output file and then using `exporter.from_filename` method to export to HTML. That does seem to work fine. Not a great solution though.

**Comment by sebnil** [comment] 2015-04-25 21:58
I ran into the same problem. I wanted to do this:
runipy -o test_notebook.ipynb --html run_and_plot_bias.html

Which did not work. I solved it by running two commands after each other:
runipy -o ../test_notebook.ipynb
ipython nbconvert ../test_notebook.ipynb --to html

**Comment by ACampbell22** [comment] 2015-08-05 17:31
Running the notebook and then converting it gives me a HTML file of the notebook as of it's last checkpoint. The cell output from the runipy execution is not included.

**Comment by twiecki** [comment] 2015-08-27 08:42
Just ran into the same issue. @sebnil's fix seems to work.

**Comment by jakirkham** [comment] 2015-10-16 19:44
Thanks for reporting this.

I was able to reproduce this from a simple test notebook. I agree that this is an issue when trying to support multiple formats, which makes me think about this ( https://github.com/paulgb/runipy/issues/78 ) again.

I will definitely need to think about how I would like to fix this.

**Comment by kbroughton** [comment] 2015-10-28 17:21
I needed to run this from within python and prefer not to use subcommands.
Two code changes to notebook_runner.py fixed it for me:
Would you like a PR?

    def run_cell(self, cell):
        """Run a notebook cell and update the output of that cell in-place."""
        print("CELL: " + str(cell))
        if 'input' in cell:
            cell_source = cell.input
        else:
            cell_source = cell.source
        logging.info('Running cell:\n%s\n', cell_source)

{code}
    def iter_code_cells(self):
        """Iterate over the notebook cells containing code."""
        if 'worksheets' in self.nb:
            for ws in self.nb.worksheets:
                for cell in ws.cells:
                    if cell.cell_type == 'code':
                        yield cell
        else:
            for cell in self.nb.cells:
                if cell.cell_type == 'code':
                    yield cell
{/code}

**Comment by jakirkham** [comment] 2015-11-17 06:57
So, I believe this PR ( https://github.com/paulgb/runipy/pull/101 ) will fix the problem of outputting an HTML file. I have included tests to verify this. I am going to go ahead and close this out. However, if anyone is still running into issues with this change, please let me know and we will try to figure something out.

**Closed** 2015-11-17 06:57 UTC
Labels: bug
