### ISSUE TITLE
ImportWarning: sys.meta_path is empty

### ISSUE THREAD

**Issue by michaelaye** [paulgb/runipy#98] opened 2015-10-23 07:43 UTC
When executing a runipy -v I get a weird looking print-out with an ImportWarning:
```bash
$ runipy -v
0.1.5-py3.4.egg
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
/Users/klay6683/miniconda3/envs/py34/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
```
Environment: runipy master, installed from github, with `python setup.py install` into a python 3.4 conda environment.

**Comment by jakirkham** [comment] 2015-10-23 07:45
That is weird. Thanks for sharing. I'll take a look at it.

**Comment by jakirkham** [comment] 2015-10-23 08:20
Seems this only happens in Python 3.

**Comment by jakirkham** [comment] 2015-10-23 08:27
The `ImportWarning` appears to be due to a bug in Python 3.4.3. I can only reproduce it by installing the package with `python setup.py install` (can't reproduce by `pip` installation). This has been corrected in Python 3.5. See more details here. ( https://bugs.python.org/issue21049 )

**Comment by jakirkham** [comment] 2015-10-23 08:28
The `ResourceWarning` will require more looking into, but occurs with a variety of possible installs in Python 3.

**Comment by michaelaye** [comment] 2015-10-23 08:38
Confirmed that pip install on py34 does not show the ImportWarning, thanks.

**Comment by jakirkham** [comment] 2015-10-23 08:42
Glad that helps. I think the best that can be hoped for is that these warnings are suppressed entirely. I'll look into something to help this tomorrow.

**Comment by michaelaye** [comment] 2015-10-23 23:52
I agree with suppressing the /dev/null FH warning, would be cool to get that in.

**Comment by jakirkham** [comment] 2015-10-27 15:26
After doing a little investigation, I suspect this line ( https://github.com/ipython/ipython/blob/a33a0632c00b604683aab8454983716823550407/IPython/utils/io.py#L75 ) is causing us trouble. I don't have an obvious fix, at present.

**Comment by jakirkham** [comment] 2015-10-27 15:37
So, I have come up with a patch for `ipython`, which will fix the `ResourceWarning`. See here ( https://github.com/ipython/ipython/pull/8929 ). I have applied this patch myself and verified that it fixes the problem.

**Comment by jakirkham** [comment] 2015-10-27 16:00
I am going to close this as I feel I have done all I can to resolve this at present. Feel free to give the patch a shot if you wish ( https://github.com/ipython/ipython/pull/8929 ). I'll try my best to get it merged in mainline. I have also added a backport of that patch to the iPython 3.x line ( https://github.com/ipython/ipython/pull/8930 ). Bug fixes are no longer being accepted to iPython 2.x so there is nothing we can do there.

**Closed by jakirkham** 2015-10-27 16:00 UTC
Labels: bug

**Comment by jakirkham** [comment] 2015-10-27 17:35
This aforementioned patch has been merged into iPython's 4.x. It should be available in the next release.

**Comment by michaelaye** [comment] 2015-10-27 18:34
Nice, thanks!

**Comment by jakirkham** [comment] 2016-01-05 19:00
Also, the 3.x patch was accepted and appears in the release 3.2.3. There is no release for the 4.x fit at present.
